#!/usr/bin/env python3
import os
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

repo_root = Path(__file__).parent.parent
config_path = Path(__file__).parent / "config.yaml"

with config_path.open() as f:
    config = yaml.safe_load(f)

top_level = set(config.get("top_level", []))
ignore = set(config.get("ignore", []))

# moves_to_hugo can contain plain strings or {name: {excludes: [...]}} dicts.
# Build a flat set of names for routing checks, and a separate excludes_map for
# entries that need a partial move (some children stay at the repo root).
moves_to_hugo = set()
excludes_map = {}  # name -> set of child names that stay at repo root
for _item in config.get("moves_to_hugo", []):
    if isinstance(_item, str):
        moves_to_hugo.add(_item)
    else:
        for _name, _opts in _item.items():
            moves_to_hugo.add(_name)
            if _opts and "excludes" in _opts:
                excludes_map[_name] = set(_opts["excludes"])

# Sanity-check the config itself for conflicts.
conflicts = top_level & moves_to_hugo
if conflicts:
    for name in sorted(conflicts):
        print(f"ERROR: '{name}' appears in both top_level and moves_to_hugo", file=sys.stderr)
    sys.exit(1)

errors = []

for name in os.listdir(repo_root):
    if name in ignore:
        continue

    if name in top_level:
        pass  # keep in place
    elif name in moves_to_hugo:
        pass  # will move below
    else:
        errors.append(name)

if errors:
    for name in sorted(errors):
        print(f"ERROR: '{name}' is not listed in astro_reorg/config.yaml", file=sys.stderr)
    print(f"{len(errors)} error(s) found. Update astro_reorg/config.yaml before running.", file=sys.stderr)
    sys.exit(1)

hugo_dir = repo_root / "hugo"
hugo_dir.mkdir(exist_ok=True)

moved = 0
deleted = 0
for name in sorted(os.listdir(repo_root)):
    if name in ignore or name in top_level or name == "hugo":
        continue
    src = repo_root / name
    dst = hugo_dir / name

    # A Python virtualenv bakes its own ABSOLUTE path into bin/activate, the
    # bin/python* symlinks, and pyvenv.cfg, so relocating the directory leaves
    # those pointing at the old path — activation then falls back to the system
    # Python (no project deps). A venv is a regenerable artifact, so delete it
    # rather than move it; `make` rebuilds it in place with correct paths.
    if name in excludes_map:
        # Partial move: relocate all children except the excluded ones, which
        # stay at the repo root inside the (now mostly-empty) source directory.
        excluded = excludes_map[name]
        dst.mkdir(exist_ok=True)
        children_moved = 0
        for child in sorted(src.iterdir()):
            if child.name in excluded:
                continue
            child.rename(dst / child.name)
            children_moved += 1
        print(f"Moving {name}/ -> hugo/{name}/ "
              f"({children_moved} item(s), excluding: {', '.join(sorted(excluded))})")
        moved += 1
        continue

    if (src / "pyvenv.cfg").is_file():
        print(f"Deleting venv {name} (regenerated by make in hugo/{name})")
        shutil.rmtree(src)
        deleted += 1
        continue

    print(f"Moving {name} -> hugo/{name}")
    src.rename(dst)
    moved += 1

print(f"Done. {moved} item(s) moved into hugo/, {deleted} venv(s) deleted for regeneration.")

# Split .gitignore between the root and hugo/ instead of copying it wholesale.
#
# A .gitignore is interpreted RELATIVE TO ITS OWN DIRECTORY, so — unlike
# CODEOWNERS — a moved rule needs NO "hugo/" prefix; it simply belongs in
# hugo/.gitignore. We therefore only ROUTE each line, never rewrite it, by its
# FIRST PATH SEGMENT (driven entirely by astro_reorg/config.yaml, same as CODEOWNERS):
#   first segment in moves_to_hugo  -> hugo/.gitignore only
#   first segment in top_level      -> root .gitignore only
#   first segment in neither         -> generic/pure glob, kept in BOTH
# Comments and blank lines are kept in both to preserve section readability.
def route_gitignore_segment(line):
    """Return the first path segment of a .gitignore pattern, or None for a
    comment/blank line. A leading '!' (negation) and '/' (root anchor) are
    stripped before taking segment 0; the line text itself is never altered.
    """
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    body = stripped[1:] if stripped.startswith("!") else stripped   # un-negate
    body = body.lstrip("/")                                          # un-anchor
    return body.split("/", 1)[0]


print("\nSplitting .gitignore between root and hugo/...")
gitignore = repo_root / ".gitignore"
gi_lines = gitignore.read_text().splitlines(keepends=True)

root_lines = []
hugo_lines = []
hugo_only_segments = set()   # routed off root into hugo/ (for the summary)
both_segments = set()        # in neither config list -> kept in both (surfaced)

for raw in gi_lines:
    segment = route_gitignore_segment(raw)
    if segment is None:                       # comment / blank -> keep in both
        root_lines.append(raw)
        hugo_lines.append(raw)
    elif segment in moves_to_hugo:
        # If the line's second path segment is excluded, it stays at the root.
        stripped_body = raw.strip().lstrip("!").lstrip("/")
        parts = stripped_body.split("/", 2)
        subsegment = parts[1] if len(parts) > 1 else None
        if subsegment and subsegment in excludes_map.get(segment, set()):
            root_lines.append(raw)
        else:
            hugo_lines.append(raw)
            hugo_only_segments.add(segment)
    elif segment in top_level:
        root_lines.append(raw)
    else:
        root_lines.append(raw)
        hugo_lines.append(raw)
        both_segments.add(segment)

gitignore.write_text("".join(root_lines))
(hugo_dir / ".gitignore").write_text("".join(hugo_lines))
print(f"  Written: .gitignore (root, pruned) and hugo/.gitignore "
      f"({len(hugo_only_segments)} segment(s) -> hugo/ only, {len(both_segments)} generic kept in both)")
if both_segments:
    print("  NOTE: kept in both (first path segment not in astro_reorg/config.yaml): "
          + ", ".join(sorted(both_segments)))

# Update Makefile: static/images stays at the repo root (excluded from the
# static/ partial move), so ./static/images/ must become ../static/images/
# relative to the hugo/ project root.
MAKEFILE_SUBSTITUTIONS = [
    ("@git clean -Xf ./static/", "@git clean -Xf ../static/"),
]

print("\nUpdating Makefile...")
makefile = hugo_dir / "Makefile"
if makefile.exists():
    original = makefile.read_text()
    updated = original
    for old, new in MAKEFILE_SUBSTITUTIONS:
        updated = updated.replace(old, new)
    if updated != original:
        makefile.write_text(updated)
        print("  Written: Makefile")

# Update .github/CODEOWNERS to reference paths under hugo/.
#
# CODEOWNERS is not YAML; it is a line-based format where each rule is
# "<pattern>  <owner...>". Rather than blanket str.replace() over the whole
# file (which let a short pattern like "config/" corrupt a longer one like
# "customization_config/"), we parse each line and route its pattern by its
# FIRST PATH SEGMENT. The decision is made on a whole segment, never a raw
# substring, so "config" can never match inside "customization_config" and the
# substitution list no longer has to be hand-ordered or kept in sync with the
# move list — it is derived entirely from astro_reorg/config.yaml.
def route_codeowners_pattern(pattern):
    """Rewrite one CODEOWNERS pattern for the hugo/ move.

    Returns (segment, new_pattern). new_pattern is None when the line is left
    untouched; segment is None for the global '*' owner. A leading '/'
    (repo-root anchor) is preserved; owners are never touched because we only
    ever rewrite the pattern token.
    """
    if pattern == "*":
        return None, None

    anchored = pattern.startswith("/")          # leading '/' = repo-root-anchored
    body = pattern[1:] if anchored else pattern
    segment = body.split("/", 1)[0]

    # Carried over from the original script: ".local/" is a misspelling of
    # "local/" (which moves into hugo/). Normalize the segment before routing
    # so the typo'd entry is repathed alongside the real one.
    if segment == ".local":
        body = "local" + body[len(".local"):]
        segment = "local"

    if segment not in moves_to_hugo:
        return segment, None

    # If the pattern's second segment is excluded, it stays at the root.
    rest = body[len(segment):]
    if rest.startswith("/"):
        subsegment = rest[1:].split("/", 1)[0]
        if subsegment in excludes_map.get(segment, set()):
            return segment, None

    new_body = "hugo/" + body
    return segment, (("/" + new_body) if anchored else new_body)


print("\nUpdating .github/CODEOWNERS...")
codeowners = repo_root / ".github" / "CODEOWNERS"
lines = codeowners.read_text().splitlines(keepends=True)
left_alone = set()        # first segments in neither config list (surfaced below)

changed = False
for i, raw in enumerate(lines):
    newline = "\n" if raw.endswith("\n") else ""
    line = raw[:-len(newline)] if newline else raw
    stripped = line.lstrip()
    if not stripped or stripped.startswith("#"):
        continue
    indent = line[:len(line) - len(stripped)]
    pattern = stripped.split(maxsplit=1)[0]
    rest = stripped[len(pattern):]            # original spacing + owners, verbatim
    segment, new_pattern = route_codeowners_pattern(pattern)
    if new_pattern is None:
        if segment is not None and segment not in top_level:
            left_alone.add(segment)
        continue
    lines[i] = indent + new_pattern + rest + newline
    changed = True

if left_alone:
    print("\n  NOTE: left unchanged (first path segment not in astro_reorg/config.yaml): "
          + ", ".join(sorted(left_alone)))

if changed:
    codeowners.write_text("".join(lines))
    print("  Written: CODEOWNERS")

# TODO: Update Cdocs so the reorg can support *.mdoc.md files. Until then,
# delete all *.mdoc.md files from hugo/ to avoid Hugo build errors — they are
# excluded from Hugo's ignoreFiles list (config/_default/config.yaml) but the
# source .mdoc.md files still need to be absent until Cdocs is reorg-aware.
print("\nDeleting *.mdoc.md files from hugo/...")
mdoc_files = list(hugo_dir.rglob("*.mdoc.md"))
for f in sorted(mdoc_files):
    f.unlink()
print(f"  Deleted {len(mdoc_files)} *.mdoc.md file(s).")
