site_name: "Monitoreo de Infraestructura y Aplicaciones de Datadog"
meta_title: Comenzando con Datadog
meta_description: "Datadog, el servicio líder para monitoreo a escala en la nube."
disclaimer: "Esta página aún no está disponible en inglés. Estamos trabajando en su traducción. <br> Si tiene alguna pregunta o comentario sobre nuestro proyecto de traducción actual, <a href=\"https://docs.datadoghq.com/help/\">¡no dude en comunicarse con nosotros!</a>"
announcement_banner:
  desktop_message: "<span>Únete a Datadog en DASH en NYC, del 9 al 10 de junio. | El futuro de la IA + Observabilidad comienza aquí.</span>"
  mobile_message: "<span>DASH NYC, del 9 al 10 de junio | IA + Observabilidad</span>"
  background_color: "#000000"
  custom_classes: 'dash-announcement-banner'
  external_link: https://dash.datadoghq.com/?utm_source=events&utm_medium=internal&utm_campaign=summit-202606dash&utm_term=HPbanner
translate_status_banner: "Esta traducción no está actualizada. Para la versión más reciente en inglés, haga clic aquí"
site_support_banner: "Este producto no es compatible con su <a href=\"/getting_started/site\">sitio de Datadog</a> seleccionado."
