DirectoryPath: "public"
# FilePath: "index.html"
TestFilesConcurrently: true
CheckGeneric: false
CheckInternal: true
CheckExternal: true
CheckImages: false
CheckMailto: false
CheckInternalHash: false
CheckScripts: false
StripQueryString: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreEmptyHref: true
IgnoreExternalBrokenLinks: false
IgnoreDirs:
  - "[ja|fr]"
IgnoreURLs:
  - "[v1|v2]"
  - "play.google.com"
  - "LinkedIn.com"
  - "marketo"
  - "google(*.).html"
  - "[app|docs-staging].datadoghq.com"
