DirectoryPath: "public"

# Speeds things up but may cause errors in some cases
TestFilesConcurrently: false

# General config
CheckDoctype: false
CheckGeneric: false
CheckInternalHash: true
CheckMailto: false
CheckMeta: false
CheckScripts: false
StripQueryString: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true

# Ignore paths
IgnoreDirs:
  - api
  - fr
  - ja
IgnoreURLs:
  - /api/[v1|v2]
  - play.google.com
  - "[linkedin|twitter|instagram].com"
  - github.com
  - "[us1|us3|app|gov|learn|www|yum|apt].datadoghq.com"
  - "127.0.0.1"
  
