DirectoryPath: "public"
TestFilesConcurrently: true
CheckGeneric: false
CheckMailto: false
CheckInternalHash: true
CheckScripts: false
StripQueryString: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
IgnoreDirs:
  - "[ja|fr]"
IgnoreURLs:
  - /api/[v1|v2]
  - play.google.com
  - LinkedIn.com
  - "[us1|us3|app|gov|learn|www].datadoghq.com"
