DirectoryPath: "public"

# Speeds things up but may cause errors in some cases
TestFilesConcurrently: true

# General config
CheckDoctype: false
CheckGeneric: false
CheckInternalHash: true
CheckMailto: false
CheckMeta: false
CheckScripts: false
StripQueryString: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true

# Ignore paths
IgnoreDirs:
  - /fr
  - /ja
IgnoreURLs:
  - /api/[v1|v2]
  - play.google.com
  - LinkedIn.com
  - github.com
  - "[us1|us3|app|gov|learn|www].datadoghq.com"
