source 'https://rubygems.org'
gem 'kramdown'
gem 'nanoc'
gem 'autoprefixer-rails'
gem 'nokogiri', '~> 1.6.7.1'
gem 'w3c_validators'
gem 'rake'
gem 'builder'
gem 'dogapi', '~> 1.20.0'
gem 'rouge'
gem 'oj'
gem 'nanoc-toolbox'
gem 'video_info'
gem 'sassc'
gem 'nanoc-cachebuster'
gem 'octokit'
group :development do
  gem 'guard-nanoc'
  gem 'guard-livereload'
  gem 'guard-rack'
  gem 'rack-contrib'
  gem 'rack-livereload'
  gem 'guard-rake'
  gem 'digest'
  gem 'adsf'
end
