source 'https://rubygems.org'
gem 'kramdown'
gem 'nanoc'
gem 'nokogiri'
gem 'w3c_validators'
gem 'rake'
gem 'builder'
gem 'dogapi', '~> 1.13.0'
gem 'rouge'
gem 'oj'
gem 'nanoc-toolbox'
group :development do
  gem 'guard-nanoc'
  gem 'guard-livereload'
  gem 'guard-rack'
  gem 'rack-contrib'
  gem 'rack-livereload'
  gem 'guard-rake'
end
