source "https://rubygems.org"
gem 'adsf'
gem 'kramdown'
gem 'mime-types'
gem 'nanoc'
gem 'nokogiri'
gem 'pygmentize'
gem 'systemu'
gem 'w3c_validators'
gem 'rake'
gem 'builder'
gem 'guard-nanoc'
gem 'timers'
gem 'dogapi', '~> 1.8.1'
