# make

# config
CONFIG_FILE := Makefile.config
include $(CONFIG_FILE)

.PHONY: start
start:
	GITHUB_TOKEN=${GITHUB_TOKEN} \
  LANGS_TO_IGNORE=${LANGS_TO_IGNORE} \
	docker-compose -f ./docker-compose-docs.yml up

.PHONY: stop
stop:
	docker-compose -f ./docker-compose-docs.yml down