extends: existence
message: "In general, use American spelling instead of '%s'."
link: 'https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md'
ignorecase: true
level: warning
tokens:
  - '(?:\w+)nised?'
  - '(?:\w+)logue'
