
extends: existence
message: "Avoid en dashes ('–'). For hyphenated words, use a hyphen ('-').\nFor parenthesis, use an em dash ('—')."
link: "https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#dashes"
nonword: true
level: error
action:
  name: edit
  params:
    - replace
    - '-'
    - '—'
tokens:
  - '–'
