extends: existence
message: "Avoid vague link text like '%s' unless paired with other descriptive text."
link: 'https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#links'
ignorecase: true
scope: link
level: warning
tokens:
  - here
  - this
  - ^page$
