extends: existence
message: "Avoid vague link text like '%s'."
link: 'https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#links'
ignorecase: true
scope: link
level: error
tokens:
  - here
