extends: existence
message: "Avoid first-person pronouns such as '%s'."
link: "https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#pronouns"
level: warning
nonword: true
tokens:
  - (?:^|\s)I\s
  - (?:^|\s)I,\s
  - \bI'm\b
  - \b[Mm]e\b
  - \b[Mm]y\b
  - \b[Mm]ine\b
  - \b[Ww]e\b
  - we'(?:ve|re)
  - \b[Uu]s\b
  - \b[Oo]ur\b
  - let's
