extends: substitution
message: "Use '%s' instead of '%s'."
link: "https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#words-and-phrases"
ignorecase: true
level: warning
nonword: true
action:
  name: replace
swap:
  # bad: good
  '\“': '\"'