#!/usr/bin/env python

import os

int_md = filter(lambda x: x.endswith('.md'), os.listdir('content/en/integrations'))
int_png = filter(lambda x: x.endswith('.png'), os.listdir('static/images/integrations_logos'))
int_ignore = ['_index.png',
              'agent_metrics.png',
              'azure_storage.png',                # Azure will deprecate soon
              'azure_diagnostic_extension.png',   # Integration not recommended
              'datadog_checks_base.png',
              'datadog_checks_dev.png',
              'datadog_checks_downloader.png',
              'datadog_checks_tests_helper.png',
              'docs.png',
              'dotnetclr.png',
              'gitlab_runner.png',
              'hbase_regionserver.png',
              'hipchat.png',                      # Hipchat service EOL was Feb 15, 2019
              'integration.png',
              'integrations-extras.png',
              'kube_proxy.png',
              'logos.png',
              'mesos_slave.png',
              'oom_kill.png',
              'riak_repl.png',
              'sendmail.png',                     # No logo available
              'sortdb.png',
              'snmpwalk.png',
              'stunnel.png',
              'tcp_queue_length.png',
              'unbound.png',                      # No logo available
              'upsc.png'
              ]

for md in int_md:
  png = md.split('.')[0] + '.png'
  if png not in int_ignore:
    if png not in int_png:
      print(png)
