menu:
  partners:
    - name: Getting Started
      url: /partners/getting_started/
      identifier: getting-started
      weight: 1
    - name: Laying the Groundwork
      url: /partners/getting_started/laying-the-groundwork/
      identifier: laying-the-groundwork
      parent: getting-started
      weight: 10
    - name: Data Intake
      url: /partners/getting_started/data-intake/
      identifier: data-intake
      parent: getting-started
      weight: 20
    - name: Delivering Value
      url: /partners/getting_started/delivering-value
      identifier: delivering-value
      parent: getting-started
      weight: 30
    - name: Billing and Usage Reporting
      url: /partners/getting_started/billing-and-usage-reporting/
      identifier: billing-and-usage-reporting
      parent: getting-started
      weight: 40
    - name: Sales Enablement
      url: /partners/sales-enablement/
      identifier: sales-enablement
      weight: 2


