targetSystem: windows
datadog:
  kubeStateMetricsEnabled: false
  orchestratorExplorer:
    enabled: false
  logs:
    enabled: false
  apm:
    socketEnabled: false
    portEnabled: true
  processAgent:
    enabled: false
agents:
  rbac:
    create: false
    serviceAccountName: datadog-agent
clusterAgent:
  enabled: false
