targetSystem: windows
datadog:
  kubeStateMetricsEnabled: false
  orchestratorExplorer:
    enabled: false
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: false
    portEnabled: true
  processAgent:
    enabled: true
    processCollection: true
  networkMonitoring:
    enabled: true
  securityAgent:
    compliance:
      enabled: false
    runtime:
      enabled: false
agents:
  rbac:
    create: false
    serviceAccountName: datadog-agent
clusterAgent:
  enabled: false
