datadog:
  kubeStateMetricsEnabled: false
  processAgent:
    enabled: true
  networkMonitoring:
    enabled: true
  orchestratorExplorer:
    enabled: false
agents:
  rbac:
    create: false
    serviceAccountName: datadog-agent
clusterAgent:
  enabled: false
