datadog:
  kubeStateMetricsEnabled: false
  orchestratorExplorer:
    enabled: false
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: true
    portEnabled: true
  processAgent:
    enabled: false
agents:
  rbac:
    create: false
    serviceAccountName: datadog-agent
clusterAgent:
  enabled: false
