init_config:
instances:
#    -   name: My_first_service
#        url: http://someurl
#        username: user
#        password: pass
#        timeout: 1

#    -   name: My_second_service
#        url: https://otherurl
