# Allows ddoghq/datadog-api-spec CI to look up its generated documentation PR.
issuer: https://token.actions.githubusercontent.com

subject: repo:ddoghq/datadog-api-spec:pull_request

claim_pattern:
  event_name: pull_request
  job_workflow_ref: ddoghq/datadog-api-spec/\.github/workflows/ci-cd\.yml@refs/pull/[0-9]+/merge
  ref: refs/pull/[0-9]+/merge
  repository: ddoghq/datadog-api-spec

permissions:
  pull_requests: read
