# Allows ddoghq/datadog-api-spec to close generated documentation PRs and delete branches.
issuer: https://token.actions.githubusercontent.com

subject: repo:ddoghq/datadog-api-spec:pull_request

claim_pattern:
  base_ref: master
  event_name: pull_request
  job_workflow_ref: ddoghq/datadog-api-spec/\.github/workflows/merged\.yml@refs/(heads/master|pull/[0-9]+/merge)
  ref: refs/(heads/master|pull/[0-9]+/merge)
  repository: ddoghq/datadog-api-spec

permissions:
  contents: write
  pull_requests: write
