issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/documentation:ref:refs/heads/master

claim_pattern:
  event_name: schedule
  ref: refs/heads/master
  ref_protected: "true"
  job_workflow_ref: DataDog/documentation/\.github/workflows/version_getter_shared\.yml@refs/heads/master

permissions:
  contents: write
  pull_requests: write