issuer: https://token.actions.githubusercontent.com

subject: "repo:DataDog/websites-modules:pull_request"

permissions:
  contents: write
  pull_requests: write

claim_pattern:
  repository: "DataDog/websites-modules"
  ref_type: "branch"
  # job_workflow_ref: DataDog/websites-modules/.github/workflows/workflow_automation.yml@refs/heads/main
  event_name: "pull_request"