on:
    schedule:
      # At 08:00 on every day-of-week from Monday through Friday.
      - cron: "0 7 * * 1-5"
    workflow_dispatch: # allows manual trigger
  
jobs:
    call-version-getter-shared-workflow:
        permissions:
            contents: read
            pull-requests: write
        uses: Datadog/documentation/.github/workflows/version_getter_shared.yml@fc972275dd6ac5ac1e519864a4e8ff25778f66af
        with:
            url: https://api.datadoghq.com/api/v2/on-prem-management-service/runner/latest-image
            file-name: private_action_runner_version.json